# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  simple_gripper_left_driver_joint:
    has_velocity_limits: true
    max_velocity: 1.91986177778
    has_acceleration_limits: false
    max_acceleration: 0
  simple_gripper_left_follower_joint:
    has_velocity_limits: true
    max_velocity: 1.91986177778
    has_acceleration_limits: false
    max_acceleration: 0
  simple_gripper_left_spring_link_joint:
    has_velocity_limits: true
    max_velocity: 1.91986177778
    has_acceleration_limits: false
    max_acceleration: 0
  simple_gripper_right_driver_joint:
    has_velocity_limits: true
    max_velocity: 1.91986177778
    has_acceleration_limits: false
    max_acceleration: 0
  simple_gripper_right_follower_joint:
    has_velocity_limits: true
    max_velocity: 1.91986177778
    has_acceleration_limits: false
    max_acceleration: 0
  simple_gripper_right_spring_link_joint:
    has_velocity_limits: true
    max_velocity: 1.91986177778
    has_acceleration_limits: false
    max_acceleration: 0