sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu

install:
    - git clone https://github.com/durovsky/siemens_cp1616.git
    - git clone --recursive https://github.com/davetcoleman/ros_control_boilerplate.git
    - git submodule update --init --recursive
    - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script: 
- source .ci_config/travis.sh
